language: python
python: 3.6

services: mysql

install: pip3 install -r requirements.txt

before_script:
  - mysql -u root -e "create database travis_test;"
  - mysql -u root -e "create user travisci identified by 'travisci'; grant all on travis_test.* to travisci;"

script:
  - python3 setup.py -u travisci -p travisci -d travis_test -h localhost
  - python3 add_feed.py -a Y -u https://hackaday.com/blog/feed/
  - python3 add_feed.py -a Y -u https://phys.org/rss-feed/
  - python3 add_feed.py -a Y -u https://www.wired.com/feed/rss
  - python3 runner.py