language: python
python: 3.6

services: 
#  - cassandra
#  - couchdb
  - elasticsearch
  - memcached
#  - mongodb
#  - mariadb
  - mysql
#  - postgresql
#  - rabbitmq
  - redis
#  - riak

install: pip3 install -r requirements.txt

before_script:
  - mysql -u root -e "create database travis_test;"
  - mysql -u root -e "create user travisci identified by 'travisci'; grant all on travis_test.* to travisci;"

script:
  - python3 setup.py --help
  - python3 setup.py -u travisci -p travisci -d travis_test -h localhost
  - python3 add_feed.py -u https://phys.org/rss-feed/ -a
  - python3 add_feed.py -u https://hackaday.com/blog/feed/ -a
  - python3 add_feed.py -u https://www.wired.com/feed/rss -a
  - python3 runner.py